name: Build and Publish Docker Image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:${{ github.ref }} .
          docker tag ${{ github.repository }}:${{ github.ref }} ${{ github.repository }}:latest
      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image to GitHub Packages
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}:${{ github.ref }}
          docker push docker.pkg.github.com/${{ github.repository }}:latest
